platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

source 'https://github.com/VIPAAR/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'SampleObjC' do
  pod 'HLSDK', :git  => 'https://github.com/VIPAAR/lime-ios-sdk.git', :tag => '13.6.1'
  #Override the deployment targets of all pods
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end

