platform :ios, '14.0'
install! 'cocoapods', :disable_input_output_paths => true
# ignore all warnings from all pods
inhibit_all_warnings!
use_modular_headers!

source 'https://github.com/VIPAAR/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'SampleObjC' do
                    
  pod 'HLSDK', '16.4.2'
  #Override the deployment targets of all pods
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        
        # Disable swift module interface verification due to a swift bug of Xcode 14.3
        # https://vipaar.atlassian.net/browse/IOS-2992
        # https://github.com/apple/swift/issues/64669
        swift_flags = "-no-verify-emitted-module-interface"
        # Load the existing xcconfig file
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)

        # Find and replace the OTHER_SWIFT_FLAGS line, or add it if it doesn't exist
        if xcconfig.match(/^OTHER_SWIFT_FLAGS/)
            xcconfig.gsub!(/^(OTHER_SWIFT_FLAGS\s*=.*)$/, '\1 ' + swift_flags)
        else
            xcconfig << "\nOTHER_SWIFT_FLAGS = $(inherited) #{swift_flags}"
        end

        # Write the updated xcconfig file
        File.write(xcconfig_path, xcconfig)
      end
    end
  end
end


