platform :ios, '12.0'

# ignore all warnings from all pods
inhibit_all_warnings!

source 'https://github.com/VIPAAR/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'SampleSwift' do
  pod 'HLSDKSwift', :path => $(HLSDK_SWIFT_DIR)
  
  # this line is important to make PromiseSwift work
  pod 'PromisesObjC', '1.2.8', :modular_headers => true

  #Override the deployment targets of all pods
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end


