apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

// You can configure your environment variables in gradle.properties,
// or you can set them by overriding the default values below.
if (!project.hasProperty('GALDR_HOST')) {
    ext {
        GALDR_HOST = "http://192.168.1.32:8777"
    }
}
if (!project.hasProperty('GALDR_API_KEY')) {
    ext {
        GALDR_API_KEY = "invalid_key"
    }
}

kotlin {
    jvmToolchain 17
}

android {
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        applicationId "com.vipaar.lime.samplehl"
        minSdkVersion 28
        targetSdkVersion project.TARGET_ANDROID_SDK_VERSION.toInteger()
        versionCode 1
        versionName "1.0"
        buildConfigField("String", "GALDR_HOST", "\"$GALDR_HOST\"")
        buildConfigField("String", "GALDR_API_KEY", "\"$GALDR_API_KEY\"")
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
        devasia {
            initWith debug
            matchingFallbacks = ['debug', 'release']
        }
    }

    flavorDimensions("version")
    productFlavors {
        light
    }
    buildFeatures {
        buildConfig = true
    }

    namespace 'com.vipaar.lime.samplehl'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.hlsdk.light

    implementation libs.timber
    implementation libs.material
    implementation libs.androidx.exifinterface
    implementation libs.androidx.recyclerview
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.legacy.support.core.utils

    implementation libs.volley
    implementation libs.androidx.appcompat
    testImplementation libs.junit
    androidTestImplementation(libs.androidx.junit) {
        exclude module: 'support-annotations'
    }
    implementation libs.jdeferred.android
}
